import Head from 'next/head'
import Image from 'next/image'
import { Container, Row, Col } from 'react-bootstrap'
import styles from '../styles/Home.module.css'
import MainNavbar from '../components/MainNavbar'

export default function Home() {
  return (
    <>
      <div>
        <Head>
          <title>Adrian Portales</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <MainNavbar styles={styles.navbar} />
        <main className={styles.main}>
          <Container fluid>
            <Row className={styles.mainRow}>
              <Col  xs={12} lg={7} className="mb-3" className={styles.Col}>
                <h1 >Hi, I'm Adrian</h1>
                <p>I am a Computer Science student and also a Full Stack Developer.</p>
              </Col>
              <Col xm={12} lg={4} className={styles.Col}>
                  <div id="card" className="shadow-lg  mb-5 rounded">
                    <Image className="rounded-3 w-auto" src="/profile-photo.jpg" alt="profile photo adrian portales"  width={300} height={300} /> 
                </div>
              </Col>
            </Row>
          </Container>

          <Container>
            <Row>
              <Col >
                <h2>Have an exciting project where you need some help?</h2> 
                <p> Send me over a message, and let's chat.</p>
              </Col>
            </Row>
          </Container>
        </main>

      </div>
    </>
  )
}
